Update to VST 2.12
BlockstreamResearch/simplicity pull request #200
Opened 2023-11-07 17:06 UTC by roconnor-blockstream

2023-11-07 17:08 UTC, roconnor-blockstream commented
@uncomputable can you test out the manual build instructions?  If you look at the `.nix` files you can see that I had to engage `IGNORECOMPCERTVERSION=true` to get this all to work.  However, I suspect that if one uses `opam` they will not have this problem.

2023-11-09 17:03 UTC, uncomputable reviewed
b3351f04846a1c75299b9a387613aa6235d883a9: The changes look good and build on my machine. I will try the manual build next.

2023-11-10 13:25 UTC, uncomputable commented on README.md
>  1. `make -j$(nproc) default_target sha`
```
$ make -j$(nproc) default_target sha
Makefile:131: *** COMPCERT VERSION MISMATCH: COMPCERT_VERSION=version=3.12 but /home/user/.opam/default/lib/coq/user-contrib/compcert/VERSION=version=3.11.  Stop.
```

I had ignore this conflict, like in nix. The compcert version seems to be fixed to the Coq version, so I don't see another workaround.

```
export IGNORECOMPCERTVERSION=true
```

2023-11-10 13:27 UTC, uncomputable requested changes
b3351f04846a1c75299b9a387613aa6235d883a9: Let's update the README. The rest looks good. I successfully built the Coq project manually.

2023-11-15 17:16 UTC, uncomputable commented
Everything builds on my end.

2023-11-15 17:48 UTC, uncomputable approved these changes
ACK dedac3ed39c13eccf6f956bd648d20e6a316a1f5

2023-11-15 18:44 UTC, merged