Make separate jet lib
BlockstreamResearch/simplicity pull request #215
Opened 2024-01-14 11:51 UTC by uncomputable

Only a subset of files is required for jet execution. Our goal is to port this subset for WASM.

rust-simplicity-sys doesn't call the local Makefile, but a target for jets will make it easier to track WASM compatibility.

# Current progress

I identified a closed subset of files that includes all jet implementations.

[rust-simplicity-sys](https://github.com/uncomputable/rust-simplicity/tree/only-jets) uses the same set of files and successfully runs on x86_64.

# Limitations

There are no unit tests because the parsing of programs etc. is not included.

Elements transaction environments cannot be built because allocations were removed.

[rust-simplicity-sys](https://github.com/uncomputable/rust-simplicity/tree/only-jets) doesn't compile on WASM.

2024-01-16 15:47 UTC, apoelstra commented
LGTM though needs to be tied into the nix buildscripts somehow in order for me to test it.

2024-02-02 22:51 UTC, roconnor-blockstream commented
I'm thinking of co-mingling the request for wrappers with this PR, so that we get a lib of wrapped jets, which use pointer arguments for everything.

2024-02-03 12:29 UTC, uncomputable commented
The changes in this PR are not used in the Rust FFI. Happy to convert this PR to draft until we know what we want from libsimplicity.

2024-02-03 17:29 UTC, roconnor-blockstream commented
Okay, this is my proposal.

@apoelstra The makefile will by default build the jets library.

It is untested as a static library.  I toyed with the idea of linking it with the Haskell code, but it seems just better to have Haskell compile the C code by itself thank to convince it to use a static library.  I suspect the same will be true with Rust bindings.

2024-02-05 16:29 UTC, apoelstra commented
Sounds good to me.

Re "just compiling the C code by itself" -- this does, in effect, create a static library. Just not one that was built through the Makefile.

2024-02-05 17:41 UTC, roconnor-blockstream commented on C/wrappedJets/wrappers.h
>  bool c_##jet(frameItem* dst, const frameItem* src) {                                                                          \
The `assert`s in this file (below the fold) should be changed to some form of `simplicity_assert`s.

2024-02-06 08:47 UTC, uncomputable commented
Requiring a Haskell environment to build the C library would be a mess. Let's keep the in-Haskell-generated C files.

2024-02-06 18:02 UTC, apoelstra approved these changes
ACK 34fe6f9127d1e22570a8d904672905b628fbaf8b

2024-02-08 23:15 UTC, roconnor-blockstream requested changes

2024-02-08 23:15 UTC, roconnor-blockstream commented on C/wrappedJets/wrappers.h
> +  simplicity_assert (!result || 0 == dst->offset);                                                                                       \
let's make these `simplicity_debug_assert`s.

2024-02-09 13:45 UTC, apoelstra approved these changes
ACK 9d2bda842240c3243faddc91752216cea0db5e99

2024-02-09 21:58 UTC, uncomputable commented on C/wrappedJets/wrappers.h
> +#include "simplicity_assert.h"
```suggestion
#include "../simplicity_assert.h"
```
Doesn't compile for me otherwise.

2024-02-09 21:58 UTC, roconnor-blockstream commented
Upon review, this assert needed a bit more care.  The assert is only being used specifically in the context of Haskell testing of jets, where a (Simplicity) frame is allocated of exactly the right size to fit the jet output.  In other contexts the conditions of the assertion might be fine.

2024-02-09 22:42 UTC, roconnor-blockstream commented on C/wrappedJets/wrappers.h
>  bool c_##jet(frameItem* dst, const frameItem* src, const txEnv* env) {                                                        \
Maybe we need to forward declare `txEnv` here?

2024-02-10 02:51 UTC, uncomputable commented on C/wrappedJets/elements/jets.c
>  WRAP_(version)
> `COREWRAP_(calculate_issuance_entropy)`

Why are certain Elements jets wrapped without environment? Are those precisely the jets that don't read from the environment?

On the Rust side we always pass the environment to the jet. There is no way of knowing which jets read and which don't read from the environment. If it's not too much work on the Haskell side, let's wrap all Elements jets using `WRAP_`.

2024-02-12 13:22 UTC, roconnor-blockstream commented
I think it is time to abort this PR as it is.  The Haskell code just doesn't do what we want.  It has special `core` jet wrappers that allow jets to be tested with no environment.  The Haskell code has special asserts are that valid for its use case, but that do not hold in general.

Instead we should go back to making a second, similar set of wrappers for use in Rust.  Those wrappers can either be added to the Rust project or the C project, whichever you think is best.  If they are added to the C project we can place them in the jet library.

2024-02-13 00:07 UTC, uncomputable commented
I close this PR because Haskell and Rust need different sets of jet wrappers.

A better approach is to generate Rust jet wrappers inside the FFI using the Haskell code generators in #218.

2024-02-13 00:08 UTC, closed without merging