Update gitignore
BlockstreamResearch/simplicity pull request #219
Opened 2024-02-01 22:54 UTC by uncomputable

Ignore more temporary files because `git status` displays dozens of lines on my end.

2024-02-01 23:05 UTC, roconnor-blockstream requested changes

2024-02-01 23:05 UTC, roconnor-blockstream commented on .gitignore
> +dist-newstyle
While we are at in can you add under `Haskell`

    cabal.project.local

2024-02-01 23:05 UTC, roconnor-blockstream commented on .gitignore
>  *.vos
While we are at in can you add under `Coq`

    /Coq/*CoqMakefile*
    *.crashcoqide
    alectryon-doc

2024-02-02 13:14 UTC, uncomputable commented
I added your suggestions and some more Coq files to the ignored list.

2024-02-02 20:13 UTC, roconnor-blockstream approved these changes
LGTM

2024-02-02 20:13 UTC, merged